# Generated by Django 4.0.5 on 2022-06-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulanceprovider',
            name='username',
            field=models.CharField(default='provider', max_length=50),
        ),
    ]
