# Generated by Django 4.0.5 on 2022-06-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulanceapp', '0002_ambulanceprovider_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulanceprovider',
            name='username',
        ),
    ]
