# Generated by Django 4.0.5 on 2022-06-24 01:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulanceapp', '0005_alter_ambulanceprovider_stripe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='images'),
        ),
        migrations.AddField(
            model_name='ambulanceprovider',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='images'),
        ),
    ]
