# Generated by Django 4.0.5 on 2022-06-24 02:05

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ambulanceapp', '0007_remove_account_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
